name: Build VSIX

on:
  push:
    branches:
      - main
      - 'copilot/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # Run daily at 00:00 Beijing Time (16:00 UTC, UTC+8)
    - cron: '0 16 * * *'

permissions:
  contents: write

jobs:
  build-vscode-extension:
    name: Build VSCode Extension
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: kotlin-vscode/package-lock.json

      - name: Install dependencies
        working-directory: kotlin-vscode
        run: npm ci

      - name: Compile extension
        working-directory: kotlin-vscode
        run: npm run compile

      - name: Create dummy LSP server archive
        run: |
          # Create a minimal dummy zip to satisfy the unpack-server script
          mkdir -p /tmp/dummy-lsp
          touch /tmp/dummy-lsp/.gitkeep
          cd /tmp && zip -r dummy-lsp.zip dummy-lsp/

      - name: Package extension
        working-directory: kotlin-vscode
        env:
          LSP_ZIP_PATH: /tmp/dummy-lsp.zip
        run: |
          # Install vsce globally
          npm install -g @vscode/vsce

          # Get version from package.json
          VERSION=$(node -p "require('./package.json').version")

          # Package the extension
          # The vscode:prepublish script will run which packages the extension and unpacks the dummy server
          vsce package "$VERSION" --out "../kotlin-vscode-${VERSION}.vsix"

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: kotlin-vscode-*.vsix
          retention-days: 30

      - name: List generated files
        run: |
          echo "Generated VSIX files:"
          ls -lh kotlin-vscode-*.vsix

      - name: Push artifacts to release branch
        if: github.event_name == 'schedule'
        run: |
          # Configure git
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          
          # Create or checkout release branch
          git fetch origin
          if git ls-remote --heads origin | grep -q '^refs/heads/release$'; then
            git checkout -b release origin/release
          else
            git checkout --orphan release
            git rm -rf .
          fi
          
          # Copy VSIX files to release branch
          # First, remove any old VSIX files
          rm -f *.vsix
          # Find and copy new VSIX files from the workspace root
          if ls ../kotlin-vscode-*.vsix 1> /dev/null 2>&1; then
            cp ../kotlin-vscode-*.vsix .
          else
            find .. -maxdepth 2 -name "kotlin-vscode-*.vsix" -not -path './\*' -exec cp {} . \;
          fi
          
          # Add and commit artifacts
          if ls *.vsix 1> /dev/null 2>&1; then
            git add *.vsix
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            git commit -m "Build artifacts from ${TIMESTAMP} (${GITHUB_SHA:0:7})"
            
            # Push to release branch
            git push origin release
          else
            echo "No VSIX files found to commit"
            exit 1
          fi
